import requests

SUPABASE_URL = "https://qknsehkdtfxpziaexdxn.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFrbnNlaGtkdGZ4cHppYWV4ZHhuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzgyNTI2MDQsImV4cCI6MjA5MzgyODYwNH0.DiawWv5LQ4OSF1pO2pH8yCY-osh5PUsti5nPAbDw8g0"

# Note: Supabase tables are usually created via the Dashboard UI or SQL Editor.
# This script is just a reminder of the structure needed.

print("To setup Supabase, please run the following SQL in your Supabase SQL Editor:")
print("""
CREATE TABLE tb_sensor (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    suhu FLOAT NOT NULL,
    ph FLOAT NOT NULL,
    kekeruhan FLOAT NOT NULL,
    waktu TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE tb_prediksi (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sensor_id BIGINT REFERENCES tb_sensor(id) ON DELETE CASCADE,
    status_keberhasilan TEXT,
    estimasi_waktu_tetas FLOAT,
    probabilitas FLOAT,
    waktu_prediksi TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
""")
